### ISSUE TITLE
Get 411 error code when OAuth request token 

### ISSUE THREAD

**Issue by xinlishang** [tripit/api#103]
I downloaded the Java Language Bindings from the web link http://tripit.github.io/api/doc/v1/index.html#authentication_section. And I have valid consumer token and secret which I just applied 30 minutes ago. When I run OAuthAccessTokenGetter in the package with the consumer token/secret I just had, I got error code 411. I checked it and means "The Content-Length header was not specified". I am not sure where is wrong? I believe it must have been specified by OAuthProvider. If not, please let me know where to specify it.  Below is the output of the app. 

fetching unauthorized request token...
Exception in thread "main" oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Server returned HTTP response code: 411 for URL: https://api.tripit.com/oauth/request_token
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:214)
    at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:69)
    at com.tripit.auth.OAuthAccessTokenGetter.main(OAuthAccessTokenGetter.java:72)
Caused by: java.io.IOException: Server returned HTTP response code: 411 for URL: https://api.tripit.com/oauth/request_token
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
    at oauth.signpost.basic.HttpURLConnectionResponseAdapter.getContent(HttpURLConnectionResponseAdapter.java:18)
    at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:228)
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:189)
    ... 2 more
Caused by: java.io.IOException: Server returned HTTP response code: 411 for URL: https://api.tripit.com/oauth/request_token
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at java.net.HttpURLConnection.getResponseCode(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
    at oauth.signpost.basic.HttpURLConnectionResponseAdapter.getStatusCode(HttpURLConnectionResponseAdapter.java:22)
    at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:178)
    ... 2 more

**Comment by xinlishang** [comment]
This is resolved by replacing DefaultOAuthProvider with CommonsHttpOAuthProvider

**Comment by tariqislam** [comment]
Thank you for providing a solution to this issue. If you don't mind, feel free to provide a pull request and I will incorporate your changes into the Java API binding.

Thanks!

Tariq

**Comment by xinlishang** [comment]
Sorry I am late. Sure. The code below is what I changed. just comment out the defaultOauthProvider and change it to    CommonsHttpOAuthProvider. 
    //OAuthProvider provider = new DefaultOAuthProvider(requestTokenUrl, accessTokenUrl, authorizeUrl);
        OAuthProvider provider = new CommonsHttpOAuthProvider(requestTokenUrl, accessTokenUrl, authorizeUrl);

**Comment by xinlishang** [comment]
I just published the change on the forum. Hope it helps. 

Date: Wed, 29 Jan 2014 09:52:01 -0800
